import os
import re
import urllib.parse
import json

workspace = "/Users/yangchen/GoogleDrive/My/My.Github/OnlineTools"

files_to_parse = {
    "OnlineTools.md": "Tools",
    "InteractiveWebpages.md": "Webpages",
    "OnlineCourses.md": "Courses",
    "OnlineBooks.md": "Books"
}

data = []

# Regex to match Markdown links: [Title](URL)
link_regex = re.compile(r'^\[([^\]]+)\]\((https?://[^\)]+)\)\s*(.*)', re.DOTALL)

for filename, category in files_to_parse.items():
    filepath = os.path.join(workspace, filename)
    if not os.path.exists(filepath):
        print(f"File not found: {filepath}")
        continue
        
    print(f"Parsing {filename}...")
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
        
    # Split content by markdown H2 headings: "## "
    blocks = content.split("\n## ")
    # The first block is the file title/header, we skip it
    for block in blocks[1:]:
        block = block.strip()
        if not block:
            continue
            
        # Match the link and description
        match = link_regex.match(block)
        if match:
            title = match.group(1).strip()
            url = match.group(2).strip()
            desc_raw = match.group(3).strip()
            
            # Clean up description
            # Remove HTML img tags
            desc_clean = re.sub(r'<img[^>]*>', '', desc_raw)
            # Remove double asterisks and other markdown syntax for clean text
            desc_clean = re.sub(r'\*\*([^*]+)\*\*', r'\1', desc_clean)
            desc_clean = re.sub(r'>\s*Usage:\s*', 'Usage: ', desc_clean)
            # Replace markdown links in description [text](url) -> text
            desc_clean = re.sub(r'\[([^\]]+)\]\([^\)]+\)', r'\1', desc_clean)
            desc_clean = desc_clean.replace("`", "")
            desc_clean = desc_clean.strip()
            
            # Extract domain for favicon
            try:
                parsed_url = urllib.parse.urlparse(url)
                domain = parsed_url.netloc
            except Exception:
                domain = ""
                
            data.append({
                "title": title,
                "url": url,
                "domain": domain,
                "category": category,
                "description": desc_clean if desc_clean else "No description available."
            })
        else:
            print(f"  Could not match block: {block[:50]}...")

# Write to data.js
js_content = f"// This file is auto-generated by build_portal.py. Do not edit directly.\nconst RESOURCES_DATA = {json.dumps(data, indent=2)};\n"

data_js_path = os.path.join(workspace, "data.js")
with open(data_js_path, "w", encoding="utf-8") as f:
    f.write(js_content)
    
print(f"Successfully generated {data_js_path} with {len(data)} items.")
