// This file is auto-generated by build_portal.py. Do not edit directly.
const RESOURCES_DATA = [
  {
    "title": "RemovePaywall",
    "url": "https://www.removepaywall.com/",
    "domain": "www.removepaywall.com",
    "category": "Tools",
    "description": "Read newspaper and bypass paywalls  \n\nThis webpage provides a clean way of reading articles by bypassing paywalls. It searches internet archives and cached versions to serve a clean, readable copy of the page. For harder paywalls, Archive.ph is a powerful alternative that takes static snapshots of pages.\nUsage: Paste the article URL on the homepage."
  },
  {
    "title": "Cobalt",
    "url": "https://cobalt.tools",
    "domain": "cobalt.tools",
    "category": "Tools",
    "description": "Download video and audio  \n\nCobalt is an open-source, privacy-respecting, and completely ad-free media downloader. It allows you to download video and audio files from YouTube, TikTok, Instagram, Twitter/X, and more without any pop-up ads, trackers, or malware.\nUsage: Paste the media URL on the homepage."
  },
  {
    "title": "Sci-Hub",
    "url": "https://sci-hub.se/",
    "domain": "sci-hub.se",
    "category": "Tools",
    "description": "Download research papers  \n \nSci-Hub is a website that provides free access to millions of research papers and books by bypassing publishers' paywalls. Note Sci-hub domains are often blocked by governments due to legal suits against them. So try to use other domain names if one does not work, such as .se, .st, .ru, .al, etc. An updated list can be found on Reddit."
  },
  {
    "title": "Sinkmoji",
    "url": "https://stinkmoji.cool/",
    "domain": "stinkmoji.cool",
    "category": "Webpages",
    "description": "An adorable face recognition experience combining face recognition and 3D modeling to celebrate Internet pop culture."
  },
  {
    "title": "Semiconductor",
    "url": "https://semiconductor.withgoogle.com/",
    "domain": "semiconductor.withgoogle.com",
    "category": "Webpages",
    "description": "Conduct an AI orchestra through your browser using your webcam and machine learning."
  },
  {
    "title": "Chrome music lab",
    "url": "https://musiclab.chromeexperiments.com/",
    "domain": "musiclab.chromeexperiments.com",
    "category": "Webpages",
    "description": "Chrome Music Lab is a website that makes learning music more accessible through fun, hands-on interactive experiments."
  },
  {
    "title": "Christmas experiments",
    "url": "https://christmasexperiments.com/",
    "domain": "christmasexperiments.com",
    "category": "Webpages",
    "description": "A digital advent calendar showcasing WebGL, canvas, and CSS3 interactive experiments by digital artists."
  },
  {
    "title": "Piano Genie",
    "url": "https://magenta.github.io/magenta-js/music/demos/piano_genie.html",
    "domain": "magenta.github.io",
    "category": "Webpages",
    "description": "An intelligent musical interface created by the Google Magenta team that allows users to play a full 88-key piano in real time using only an 8-button controller or your computer keyboard."
  },
  {
    "title": "100-Days-Of-ML-Code",
    "url": "https://github.com/Avik-Jain/100-Days-Of-ML-Code",
    "domain": "github.com",
    "category": "Courses",
    "description": "A popular 100-day curriculum and repository covering the fundamentals of Machine Learning, including math, algorithms, and practical implementations."
  },
  {
    "title": "WRF on AWS",
    "url": "https://github.com/aws-samples/aws-hpc-workshops/blob/master/README-WRF.rst",
    "domain": "github.com",
    "category": "Courses",
    "description": "A tutorial workshop for running the Weather Research and Forecasting (WRF) model on AWS High Performance Computing (HPC) environments."
  },
  {
    "title": "Time Series Visualization and Forecasting",
    "url": "https://www.digitalocean.com/community/tutorial_series/time-series-visualization-and-forecasting",
    "domain": "www.digitalocean.com",
    "category": "Courses",
    "description": "A comprehensive tutorial series by DigitalOcean on time series data visualization and forecasting using Python (pandas, statsmodels, and ARIMA models)."
  },
  {
    "title": "Machine Learning Crash Course with TensorFlow APIs",
    "url": "https://developers.google.cn/machine-learning/crash-course/",
    "domain": "developers.google.cn",
    "category": "Courses",
    "description": "Google's fast-paced, practical introduction to machine learning, featuring a series of lessons with video lectures, real-world case studies, and hands-on coding exercises."
  },
  {
    "title": "Fundamentals of Data Visualization",
    "url": "https://clauswilke.com/dataviz/",
    "domain": "clauswilke.com",
    "category": "Books",
    "description": "A comprehensive guide by Claus O. Wilke on making data visualizations that accurately reflect the data, tell a story, and look professional."
  },
  {
    "title": "Werner\u2019s Nomenclature of Colours",
    "url": "https://www.c82.net/werner/",
    "domain": "www.c82.net",
    "category": "Books",
    "description": "Nicholas Rougeux's beautiful interactive recreation of the original 1821 color guidebook with cross references, photographic examples, and modern web styling."
  },
  {
    "title": "Forecasting: Principles and Practice (2nd ed.)",
    "url": "https://otexts.com/fpp2/",
    "domain": "otexts.com",
    "category": "Books",
    "description": "or (3rd ed.)  \nAn online textbook providing a comprehensive introduction to forecasting methods, including ARIMA models, exponential smoothing, and state space models."
  },
  {
    "title": "A Programmer's Guide to Data Mining",
    "url": "http://guidetodatamining.com/",
    "domain": "guidetodatamining.com",
    "category": "Books",
    "description": "A guide to data mining, machine learning, and recommendation engines, designed in an easy-to-read, conversational textbook format."
  },
  {
    "title": "BUTTERICK\u2019S PRACTICAL TYPOGRAPHY",
    "url": "https://practicaltypography.com/",
    "domain": "practicaltypography.com",
    "category": "Books",
    "description": "A thorough, online guidebook to practical typography and page design, explaining principles of formatting, spacing, and font selection."
  },
  {
    "title": "Interpretable Machine Learning",
    "url": "https://christophm.github.io/interpretable-ml-book/index.html",
    "domain": "christophm.github.io",
    "category": "Books",
    "description": "A guide for making black box machine learning models explainable, covering feature importance, partial dependence plots, SHAP, and LIME."
  }
];
